import json
import re
from pathlib import Path


REMOVED_IDS = {
    "langenkamp",
    "albachten bahnhof",
    "marga-spiegel-straße",
    "albachten kirche",
    "hohe geist",
    "wierling",
    "rottkamp",
    "dülmener straße",
    "blomenkamp",
    "sendener stiege",
    "am kämpken",
    "alte viehstraße",
    "niederort",
    "haus ruhr",
    "alvingheide",
    "venne brücke",
    "wiedau",
    "alexianer-campus",
    "hansa-business-park",
    "kopenhagener straße",
    "antwerpener straße",
    "kannenweg",
    "alexianerweg",
    "wiedau (schulbus)",
    "inkmann",
    "roxel mitte",
    "paul-gerhardt-straße",
    "schelmenstiege",
    "dorffeldstraße",
    "burg hülshoff",
    "brookweg",
    "weißes kreuz",
    "brock 260",
    "stellmacherweg",
    "pantaleonstraße",
    "roxel hallenbad",
    "roxel alte dorfstraße",
    "pienersallee",
    "raiffeisenstraße",
    "nottulner landweg",
    "lise-meitner-straße",
    "an der kleikuhle",
    "hohenholter straße",
    "wegegabel",
    "roxel bahnhof",
    "everding",
    "zur walbeke",
    "von-holte-straße",
    "abzweig angelmodde",
    "lerschmehr",
    "grenkuhlenweg",
    "wolbecker windmühle",
    "am tiergarten",
    "sültemeyer",
    "am berler kamp",
    "wolbeck markt",
    "nogatstraße",
    "zumbuschstraße",
    "wolbeck ehrenmal",
    "juffernkamp",
    "drostenhof",
    "telgter straße / l793",
    "im bilskamp",
    "anton-aulke-straße",
    "hiltruper straße",
    "wolbeck schulzentrum",
    "tiergartenheide",
    "fronhof",
    "markfort",
    "nikolausweg",
    "holtrode",
    "kurhaus",
    "middelerstraße",
    "brandhoveweg",
    "amelsbüren süd",
    "steiner see",
    "haus heidhorn",
    "pater-kolbe-straße",
    "davertstraße",
    "am dornbusch",
    "kanalbrücke",
    "raringheide",
    "amelsbüren bahnhof",
    "siriusweg",
    "amelsbüren kirche",
    "leisnerstraße",
    "freibad hiltrup",
    "handorf kaserne",
    "dorbaum",
    "drei eichen",
    "lützowstraße",
    "in der stroth",
    "verth",
    "am hornbach",
    "am kerkamp",
    "fachklinik hornheide",
    "eichenaue",
    "overeskenhoek",
    "rieselfelder",
    "gelmer",
    "alfersheide",
    "gelmerheide",
    "hessenbusch",
    "zur eckernheide",
    "ölhafen",
    "pieper",
    "hessenweg",
    "schornheide",
    "westerheide",
    "abzweig sprakel",
    "ashölterweg",
    "sprakel nord",
    "sprakel bahnhof",
    "dreilinden",
    "sprakel mitte",
    "sprakel nienberger straße",
    "heidegrund",
    "hölkenbusch",
    "höltene schluse",
    "kleiheide",
    "langenhorster stiege",
    "im brook",
    "hangkamp",
    "sprakeler heide",
    "schlusenweg",
    "nienberger straße",
    "sprakel kapelle",
    "stefan-zweig-straße",
    "isolde-kurz-straße",
    "von-schonebeck-ring",
    "sporthalle nienberge",
    "sessendrupweg",
    "goesenweg",
    "alhardstraße",
    "friedhof",
    "hannaschweg",
    "nienberge schule",
    "hermann-hesse-straße",
    "feldstiege",
    "hägerstraße",
    "middendorf",
    "einingweg",
    "gewerbegebiet",
    "häger bahnhof",
    "vollmer",
    "vorbergs hügel",
    "schulbus",
    "uhlenbrock",
    "haus rüschhaus",
    "schonebeck",
    "hülshoffstraße",
    "hunnebeckweg",
    "körberheide",
    "averhoff / rusticus",
    "getterbach",
    "holtschulte",
    "möselerhook",
    "freibad stapelskotten",
    "stapelskotten",
    "friedhof hohe ward",
    "am rohrbusch",
    "ackermann",
    "hohenfeld",
    "friedhof altenroxel",
    "altenroxeler straße",
    "ramertsweg",
    "autobahn nord",
    "gewerbegebiet uhlenkotten",
    "haus uhlenkotten",
    "wilkinghege golfplatz",
    "am knapp",
    "am max-klemens-kanal",
    "westfälisches pferdezentrum",
    "sudmühle",
    "freibad sudmühle",
    "sudmühlenstraße",
    "dyckburgstraße",
    "windbreede",
    "grollheide",
    "hünenburg",
    "berg fidel",
    "hogenbergstraße",
    "friedenspark",
    "biederlackweg",
    "gewerbegebiet loddenheide",
    "gustav-stresemann-weg",
    "bertha-von-suttner weg",
    "verkehrsbetriebe",
    "zeisigweg",
    "delstrup",
    "böddingheideweg",
    "gymnasium st. mauritz",
    "wersebeckmannweg",
    "am breilbusch",
    "gievenbecker reihe",
}


def main() -> None:
    file_path = Path("busstops-hardcoded.js")
    source = file_path.read_text(encoding="utf-8")
    match = re.match(r"^const HARDCODED_STOPS = (.*);\s*$", source, re.S)
    if not match:
        raise RuntimeError("Unexpected format in busstops-hardcoded.js")

    data = json.loads(match.group(1))
    before = len(data)

    kept = [item for item in data if item.get("id") not in REMOVED_IDS]
    kept.sort(key=lambda item: (item.get("name") or "").lower())

    out = "const HARDCODED_STOPS = " + json.dumps(
        kept, ensure_ascii=False, separators=(",", ":")
    ) + ";\n"
    file_path.write_text(out, encoding="utf-8")

    print(f"before: {before}")
    print(f"removed list: {len(REMOVED_IDS)}")
    print(f"after: {len(kept)}")


if __name__ == "__main__":
    main()
